name: falcon_query
description: falcon_query is SQL query builder for Falcon ORM. Fast And Lightweight.
version: 0.0.2
repository: https://github.com/webdastur/falcon/tree/master/packages/falcon_query
issue_tracker: https://github.com/webdastur/falcon/issues
homepage: https://github.com/webdastur/falcon

environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.18.0
dependencies: 
  collection: ^1.15.0
