name: falcon_query

on:
  push:
    paths: 
      - "packages/falcon_query/**"
      - ".github/workflows/falcon_query.yml"
  pull_request:
    paths: 
      - "packages/falcon_query/**"
      - ".github/workflows/falcon_query.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: dart test
