name: falcon_query

on:
  push:
    paths: 
      - "packages/falcon_query/**"
      - ".github/workflows/falcon_query.yml"
  pull_request:
    paths: 
      - "packages/falcon_query/**"
      - ".github/workflows/falcon_query.yml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/falcon_query

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: |
          dart pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: packages/falcon_query/coverage/lcov.info
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
